# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
