# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_auto_20160729_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='base_url',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
