# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0003_auto_20160729_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='short_url',
            new_name='short_string',
        ),
        migrations.AlterField(
            model_name='link',
            name='base_url',
            field=models.CharField(max_length=256, unique=True, verbose_name='Base URL'),
        ),
    ]
